# -*- coding: utf-8 -*-
"""JSON Refiner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144c0crIN3IcLjqyuYY_3w9LkSIy9Azt2
"""

# =====================================================
# JSON Refiner Advanced Edition
# Complete Single File Program for Google Colab
# =====================================================

# ---------- Install Required Packages ----------
!pip install -q gradio json5 jsonschema python-dotenv pydantic

# ---------- Import Libraries ----------
import json
import json5
import re
from enum import Enum
from jsonschema import validate, ValidationError
import gradio as gr


# =====================================================
# Case Style Enum
# =====================================================

class CaseStyle(Enum):
    SNAKE_CASE = "snake_case"
    CAMEL_CASE = "camelCase"
    KEBAB_CASE = "kebab-case"
    PASCAL_CASE = "PascalCase"


# =====================================================
# JSON Refiner Core Engine
# =====================================================

class JSONRefinerCore:

    def __init__(self):
        self.conversion_log = []
        self.validation_errors = []
        self.transformation_history = []

# -----------------------------------------------------
# Type Inference System
# -----------------------------------------------------

    def infer_type(self, value):

        if value is None:
            return None

        v = value.strip().lower()

        if v in ["true","yes","on"]:
            return True

        if v in ["false","no","off"]:
            return False

        if v in ["null","none","nil","n/a","undefined"]:
            return None

        try:
            if "." in value:
                return float(value)
            else:
                return int(value)
        except:
            pass

        try:
            parsed = json5.loads(value)
            return parsed
        except:
            pass

        return value


# -----------------------------------------------------
# Case Conversion Utilities
# -----------------------------------------------------

    def split_words(self, text):
        words = re.split(r'[\s_\-]+', text)
        return [w for w in words if w]


    def to_snake_case(self, key):
        words = self.split_words(key)
        return "_".join(w.lower() for w in words)


    def to_camel_case(self, key):
        words = self.split_words(key)
        if not words:
            return key
        first = words[0].lower()
        rest = ''.join(w.capitalize() for w in words[1:])
        return first + rest


    def to_kebab_case(self, key):
        words = self.split_words(key)
        return "-".join(w.lower() for w in words)


    def to_pascal_case(self, key):
        words = self.split_words(key)
        return ''.join(w.capitalize() for w in words)


    def normalize_key(self, key, style):

        if style == CaseStyle.SNAKE_CASE.value:
            return self.to_snake_case(key)

        if style == CaseStyle.CAMEL_CASE.value:
            return self.to_camel_case(key)

        if style == CaseStyle.KEBAB_CASE.value:
            return self.to_kebab_case(key)

        if style == CaseStyle.PASCAL_CASE.value:
            return self.to_pascal_case(key)

        return key


# -----------------------------------------------------
# Parse Key Value Text
# -----------------------------------------------------

    def parse_key_value(self, text, case_style):

        result = {}

        lines = text.strip().split("\n")

        for line in lines:

            if ":" not in line:
                continue

            key,value = line.split(":",1)

            key = key.strip()
            value = value.strip()

            key = self.normalize_key(key, case_style)

            result[key] = self.infer_type(value)

        return result


# -----------------------------------------------------
# JSON Schema Validation
# -----------------------------------------------------

    def validate_schema(self, data, schema_text):

        try:

            schema = json.loads(schema_text)

            validate(instance=data, schema=schema)

            return "✅ Schema Validation Successful"

        except ValidationError as e:

            return "❌ Validation Error : " + str(e)

        except:

            return "❌ Invalid Schema"


# -----------------------------------------------------
# Required Field Validation
# -----------------------------------------------------

    def check_required_fields(self, data, required):

        fields = [f.strip() for f in required.split(",")]

        missing = []

        for f in fields:
            if f not in data:
                missing.append(f)

        if not missing:
            return "✅ All required fields present"

        return "❌ Missing Fields : " + str(missing)


# -----------------------------------------------------
# Remove Null Values
# -----------------------------------------------------

    def remove_null_values(self, data):

        return {k:v for k,v in data.items() if v is not None}


# -----------------------------------------------------
# Flatten JSON
# -----------------------------------------------------

    def flatten_json(self, data, parent_key='', sep='.'):

        items = {}

        for k,v in data.items():

            new_key = parent_key + sep + k if parent_key else k

            if isinstance(v, dict):

                items.update(self.flatten_json(v,new_key,sep))

            else:

                items[new_key] = v

        return items


# -----------------------------------------------------
# Unflatten JSON
# -----------------------------------------------------

    def unflatten_json(self, data):

        result = {}

        for key,value in data.items():

            parts = key.split(".")

            d = result

            for part in parts[:-1]:

                if part not in d:
                    d[part] = {}

                d = d[part]

            d[parts[-1]] = value

        return result


# -----------------------------------------------------
# Merge JSON Objects
# -----------------------------------------------------

    def merge_json_objects(self, j1, j2, j3):

        result = {}

        for j in [j1,j2,j3]:

            try:
                obj = json.loads(j)
                result.update(obj)
            except:
                pass

        return result


# =====================================================
# Initialize Core
# =====================================================

core = JSONRefinerCore()


# =====================================================
# Interface Functions
# =====================================================

def refine_json(text,case_style,remove_nulls,flatten):

    data = core.parse_key_value(text,case_style)

    if remove_nulls:
        data = core.remove_null_values(data)

    if flatten:
        data = core.flatten_json(data)

    return json.dumps(data,indent=4)


def validate_json(json_text,schema,required):

    try:
        data = json.loads(json_text)
    except:
        return "❌ Invalid JSON"

    r1 = ""
    r2 = ""

    if schema:
        r1 = core.validate_schema(data,schema)

    if required:
        r2 = core.check_required_fields(data,required)

    return r1 + "\n" + r2


def merge_json(j1,j2,j3):

    result = core.merge_json_objects(j1,j2,j3)

    return json.dumps(result,indent=4)


def transform_json(text,mode):

    data = json.loads(text)

    if mode == "Flatten":
        result = core.flatten_json(data)
    else:
        result = core.unflatten_json(data)

    return json.dumps(result,indent=4)


# =====================================================
# Gradio Interface
# =====================================================

with gr.Blocks(title="JSON Refiner Advanced Edition") as app:

    gr.Markdown("# JSON Refiner Advanced Edition")

# ---------------- Core Refining ----------------

    with gr.Tab("Core Refining"):

        input_text = gr.Textbox(lines=10,label="Key Value Input")

        case_style = gr.Radio(
            choices=[s.value for s in CaseStyle],
            value="snake_case",
            label="Case Style"
        )

        remove_nulls = gr.Checkbox(label="Remove Null Values")

        flatten = gr.Checkbox(label="Flatten JSON")

        output_json = gr.Code(label="Generated JSON")

        btn = gr.Button("Generate JSON")

        btn.click(refine_json,
                  inputs=[input_text,case_style,remove_nulls,flatten],
                  outputs=output_json)


# ---------------- Validation ----------------

    with gr.Tab("Validation"):

        json_input = gr.Textbox(lines=10,label="JSON Input")

        schema_input = gr.Textbox(lines=8,label="JSON Schema")

        required_input = gr.Textbox(label="Required Fields")

        validation_output = gr.Textbox(label="Validation Result")

        btn2 = gr.Button("Validate JSON")

        btn2.click(validate_json,
                   inputs=[json_input,schema_input,required_input],
                   outputs=validation_output)


# ---------------- Merge JSON ----------------

    with gr.Tab("Merge JSON"):

        j1 = gr.Textbox(lines=6,label="JSON Object 1")

        j2 = gr.Textbox(lines=6,label="JSON Object 2")

        j3 = gr.Textbox(lines=6,label="JSON Object 3")

        merge_output = gr.Code(label="Merged JSON")

        btn3 = gr.Button("Merge")

        btn3.click(merge_json,
                   inputs=[j1,j2,j3],
                   outputs=merge_output)


# ---------------- Flatten / Unflatten ----------------

    with gr.Tab("Flatten / Unflatten"):

        transform_input = gr.Textbox(lines=10,label="JSON Input")

        mode = gr.Radio(["Flatten","Unflatten"],label="Operation")

        transform_output = gr.Code(label="Output")

        btn4 = gr.Button("Transform")

        btn4.click(transform_json,
                   inputs=[transform_input,mode],
                   outputs=transform_output)


# =====================================================
# Launch Application
# =====================================================

app.launch(share=True)